Repository NREL/PVDegradationTools, pull requests merged in 2025-08, with the labels that each got.

#193 Added support for pandas dataframes to weather.map_meta
  pvdeg/weather.py
  tests/test_weather.py
Labels: enhancement

#196 Continuing Flake8
  pvdeg/__init__.py
  pvdeg/decorators.py
  pvdeg/degradation.py
  pvdeg/diffusion.py
  pvdeg/fatigue.py
  pvdeg/geospatial.py
  pvdeg/geospatialscenario.py
  pvdeg/humidity.py
  pvdeg/montecarlo.py
  pvdeg/pysam.py
  pvdeg/scenario.py
  pvdeg/spectral.py
  pvdeg/standards.py
  pvdeg/temperature.py
  pvdeg/utilities.py
  pvdeg/weather.py
  scripts/batch/inspire.py
  scripts/batch/slurmrunner.py
  tests/test_degradation.py
  tests/test_geospatial.py
  tests/test_geospatialscenario.py
  tests/test_humidity.py
  tests/test_letid.py
  tests/test_montecarlo.py
  tests/test_scenario.py
  tests/test_standards.py
  tests/test_symbolic.py
  tests/test_temperature.py
  tests/test_utilities.py
  tests/test_weather.py
Labels: documentation, enhancement, Clarity for users

#210 Improve test coverage 2.0
  .gitignore
  pvdeg/scenario.py
  pvdeg/utilities.py
  pvdeg/weather.py
  tests/data/test-scenario.json
  tests/test_collection.py
  tests/test_decorators.py
  tests/test_geospatialscenario.py
  tests/test_scenario.py
  tests/test_utilities.py
Labels: testing
